'use client';
import { useCallback, useEffect, useState } from 'react';
import { Compass, LayoutDashboard, Workflow, FlaskConical, Database, LibraryBig, History, ChartNoAxesCombined, ArrowRight, ArrowUpRight, RefreshCw, Download, Upload, ChevronRight, Check, CircleDot, SlidersHorizontal, ShieldCheck, Info, LoaderCircle, Menu, X, Play, Target, ChevronDown, CircleAlert, CircleCheck, FileSpreadsheet, Layers3 } from 'lucide-react';
import { api, post, downloadHistory } from '@/lib/api';
import type { PageId, Dashboard, Decision, Dataset, Lab, Profile, State, Factor, Bias, TrainingReport, LibraryComponent, Reward, Experiments, Num, FactorAnalysis, Curve } from '@/lib/types';
import { RevenueChart, ChannelChart, QChart, TrainingChart, ImportanceChart, ExperimentChart } from './charts';

const NAV = [
  { id: 'dashboard', title: '经营总览', icon: LayoutDashboard, url: '/' },
  { id: 'decision', title: '营销决策中心', icon: Workflow, url: '/decision/' },
  { id: 'lab', title: 'SARSA 实验室', icon: FlaskConical, url: '/lab/' },
  { id: 'experiments', title: '策略对照实验', icon: ChartNoAxesCombined, url: '/experiments/' },
  { id: 'data', title: '企业数据中心', icon: Database, url: '/data/' },
  { id: 'library', title: '营销模型库', icon: LibraryBig, url: '/library/' },
  { id: 'history', title: '决策与反馈记录', icon: History, url: '/history/' },
] as const;
const PROFILE_LABEL: Record<string,string> = { profit_maximization:'利润优先', growth_maximization:'销售增长', inventory_clearance:'库存消化', customer_retention:'客户留存', new_customer_acquisition:'新客拓展', acquisition_efficiency:'获客效率', balanced_growth:'均衡经营' };
const REWARD_LABEL: Record<string,string> = { profit_margin:'营销贡献利润率',roi:'营销 ROI',conversion_rate:'转化率',repeat_purchase_rate:'回流客户占比',inventory_turnover:'库存周转',gmv_growth:'收入增长',new_customer_ratio:'新客占比',cac:'广告 CAC',return_rate:'退货率',promotion_cost_ratio:'额外促销成本率',inventory_pressure:'库存压力',volatility:'收入波动' };
const STATUS: Record<string,string> = { draft:'待确认执行',executed:'待经营反馈',awaiting_next:'待下一动作确认',updated:'已完成学习',terminal:'周期已结束',cancelled:'已取消' };
const CATEGORY: Record<string,string> = { performance:'积极与绩效',penalty:'惩罚因子',business:'经营状态',channel:'渠道结构',external:'外部扰动',bias:'偏差信号',candidate:'候选因子' };
function fmt(v: Num | undefined, digits=2) { return v==null || !Number.isFinite(v) ? '—' : v.toLocaleString('zh-CN',{maximumFractionDigits:digits,minimumFractionDigits:digits}); }
function pct(v: Num | undefined, digits=1) { return v==null ? '—' : `${fmt(v*100,digits)}%`; }
function money(v: Num | undefined, digits=0) { return v==null ? '—' : `¥${fmt(v,digits)}`; }
function shortDate(t:string) { return new Date(t).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}); }
function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:'neutral'|'blue'|'green'|'amber'}) { return <span className={`badge ${tone}`}>{children}</span>; }
function Panel({title,subtitle,extra,children,className=''}:{title:string;subtitle?:string;extra?:React.ReactNode;children:React.ReactNode;className?:string}) {
  return <section className={`panel ${className}`}><div className="panel-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{extra}</div>{children}</section>;
}
function Empty({title,detail}:{title:string;detail?:string}) { return <div className="empty"><Layers3 size={32}/><h3>{title}</h3>{detail&&<p>{detail}</p>}</div>; }
function Notice({children,tone='blue'}:{children:React.ReactNode;tone?:'blue'|'amber'|'green'}) { return <div className={`notice ${tone}`}><Info size={16}/><div>{children}</div></div>; }
function Flow({stage=0}:{stage?:number}) { return <div className="flow">{['经营数据','语义与因子','SARSA 决策','执行与结果','Reward 反馈','策略更新'].map((x,i)=><div key={x} className={`flow-step ${i<=stage?'done':''}`}><span className="flow-number">{i<stage?<Check size={12}/>:i+1}</span><span>{x}</span>{i<5&&<ChevronRight className="flow-arrow" size={15}/>}</div>)}</div>; }

export default function Platform({initialPage}:{initialPage:PageId}) {
  const [page,setPage]=useState<PageId>(initialPage),[dashboard,setDashboard]=useState<Dashboard|null>(null);
  const [lab,setLab]=useState<Lab|null>(null),[data,setData]=useState<Dataset|null>(null),[history,setHistory]=useState<Decision[]>([]),[library,setLibrary]=useState<LibraryComponent[]>([]);
  const [record,setRecord]=useState<Decision|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[toast,setToast]=useState(''),[menu,setMenu]=useState(false);
  const refresh=useCallback(async()=>{const d=await api<Dashboard>('/dashboard');setDashboard(d);if(d.active_decision)setRecord(d.active_decision);return d;},[]);
  const run=useCallback(async(label:string,fn:()=>Promise<void>)=>{setBusy(label);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'操作失败，请重试');}finally{setBusy('');}},[]);
  useEffect(()=>{run('加载经营数据',async()=>{await refresh();});},[refresh,run]);
  useEffect(()=>{
    if(!dashboard)return;
    let cancelled=false;
    const load=async()=>{
      try{
        if(page==='lab'||page==='experiments'){const v=await api<Lab>('/lab');if(!cancelled)setLab(v);}
        if(page==='data'){const v=await api<Dataset>('/data');if(!cancelled)setData(v);}
        if(page==='history'){const v=await api<Decision[]>('/decisions');if(!cancelled)setHistory(v);}
        if(page==='library'){const v=await api<LibraryComponent[]>('/library');if(!cancelled)setLibrary(v);}
      }catch(e){if(!cancelled)setError(e instanceof Error?e.message:'加载失败');}
    };load();return()=>{cancelled=true;};
  },[page,dashboard]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);},[toast]);
  useEffect(()=>{const back=()=>{const match=NAV.find(x=>x.url===location.pathname);if(match)setPage(match.id);};window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back);},[]);
  const go=(target:PageId)=>{setPage(target);setMenu(false);setError('');window.history.pushState({},'',NAV.find(x=>x.id===target)?.url||'/');window.scrollTo({top:0});};
  const nav=NAV.find(x=>x.id===page)!;
  const reload=()=>run('刷新数据',async()=>{await refresh();setToast('已读取最新经营数据');});
  const onExecute=(d:Decision,body:unknown={})=>run('确认执行',async()=>{const x=await post<Decision>(`/decisions/${d.id}/execute`,body);setRecord(x);await refresh();setToast(x.previous_update?'下一实际动作已确认，上一轮 SARSA 更新完成':'已记录执行动作，可以提交结果');});
  const onFeedback=(d:Decision,body:unknown)=>run('计算奖励与下一状态',async()=>{const x=await post<{decision:Decision;next_decision:Decision|null}>(`/decisions/${d.id}/feedback`,body);setRecord(x.next_decision||x.decision);await refresh();setToast(x.next_decision?'结果已保存。确认下一实际动作后更新上一轮模型':'经营周期结束，终止状态更新已完成');});
  const onCancel=(d:Decision)=>run('取消草稿',async()=>{await post(`/decisions/${d.id}/cancel`);setRecord(null);await refresh();});
  const onEnd=(d:Decision)=>run('结束经营周期',async()=>{if(!d.parent_decision)return;const prev=await post<Decision>(`/decisions/${d.parent_decision}/finish`);setRecord(prev);await refresh();setToast('周期已结束；下一建议未执行，按终止状态更新');});
  const newSession=()=>run('创建演示会话',async()=>{const x=await post<{session_id:string}>('/session');localStorage.setItem('shenmou-session-v1',x.session_id);setRecord(null);setHistory([]);await refresh();setToast('已创建独立演示会话，原会话记录保留在后端');});
  return <div className="workspace">
    <aside className={`sidebar ${menu?'open':''}`}><a className="brand" href="/" onClick={e=>{e.preventDefault();go('dashboard');}}><div className="brand-mark"><Compass size={25} strokeWidth={1.6}/></div><div><strong>深谋远虑</strong><span>SHENMOU · DECISION</span></div></a>
      <div className="sidebar-caption">营销决策工作台</div><nav aria-label="主导航">{NAV.map(x=><a key={x.id} href={x.url} className={`nav-item ${page===x.id?'active':''}`} onClick={e=>{e.preventDefault();go(x.id);}}><x.icon size={18}/><span>{x.title}</span>{page===x.id&&<span className="nav-dot"/>}</a>)}</nav>
      <div className="sidebar-bottom"><div className="engine-card"><div className="engine-label"><span className="status-dot"/>DEEP SARSA</div><p>把每一次反馈<br/>变成下一次决策的依据</p><span className="engine-meta">72 维状态 · 18 个动作</span></div><div className="sidebar-footer"><span className="avatar">研</span><div><strong>竞赛研究工作区</strong><small>独立会话 · 原型 v1.0</small></div></div></div>
    </aside>
    {menu&&<div className="mobile-overlay" onClick={()=>setMenu(false)}/>}
    <div className="main-wrap"><header className="topbar"><div className="breadcrumbs"><button className="icon-button mobile-menu" aria-label="打开导航" onClick={()=>setMenu(!menu)}>{menu?<X size={20}/>:<Menu size={20}/>}</button><span>工作台</span><ChevronRight size={13}/><strong>{nav.title}</strong></div><div className="top-actions"><span className="connection"><span className={`status-dot ${dashboard?'':'off'}`}/>{dashboard?'服务已连接':'连接中'}</span><span className="top-divider"/><span className="avatar top-avatar">研</span></div></header>
      <main><div className="page-heading"><div><div className="eyebrow">MARKETING INTELLIGENCE</div><h1>{nav.title}</h1><p>{page==='dashboard'?'看清渠道表现，把经营数据带入下一轮决策。':page==='decision'?'先理解问题，再由强化学习选择动作，最后用结果验证。':page==='lab'?'查看实际训练轨迹、网络状态与因子分析。':page==='experiments'?'相同测试场景，不同策略。保留真实结果和未运行项。':page==='data'?'检查经营数据、指标口径与模型输入。':page==='library'?'可独立注册的营销组件，共同支持决策闭环。':'从经营问题到实际反馈，完整追踪每一轮决策。'}</p></div><div className="heading-actions"><button className="button subtle" onClick={reload} disabled={!!busy}><RefreshCw size={15} className={busy?'spinning':''}/>刷新</button>{page==='dashboard'&&<button className="button primary" onClick={()=>go('decision')}>开始营销决策<ArrowRight size={15}/></button>}</div></div>
        {error&&<div className="error-banner" role="alert"><CircleAlert size={17}/><span>{error}</span><button aria-label="关闭错误" onClick={()=>setError('')}><X size={16}/></button></div>}
        {toast&&<div className="toast" role="status"><CircleCheck size={17}/>{toast}</div>}
        {!dashboard?<div className="loading-page"><LoaderCircle className="spinning" size={26}/><p>{error?'暂时无法载入数据，请确认后端运行后点击刷新':'正在载入经营数据与模型…'}</p></div>:<>
          <div className="context-bar"><div className="enterprise-icon">松</div><div><strong>{dashboard.quality.source==='demo'?'三只松鼠 · 营销演示场景':'企业经营数据'}</strong><span>{dashboard.quality.source==='demo'?'合成数据，不代表企业实际经营':dashboard.quality.label}</span></div><div className="context-meta"><Badge tone="blue">{dashboard.quality.days} 天 · {dashboard.quality.rows} 行</Badge><Badge tone={dashboard.llm.available?'green':'amber'}>{dashboard.llm.available?'LLM 已配置':'规则解析 / 模板解释'}</Badge><Badge>{dashboard.training_status}</Badge></div></div>
          {page==='dashboard'&&<Overview dashboard={dashboard} onDecision={()=>go('decision')}/>}
          {page==='decision'&&<DecisionCenter dashboard={dashboard} record={record} busy={busy} run={run} onCreated={async d=>{setRecord(d);await refresh();}} onExecute={onExecute} onFeedback={onFeedback} onCancel={onCancel} onEnd={onEnd}/>}
          {page==='lab'&&(lab?<Laboratory lab={lab} busy={busy} run={run} onTrained={async()=>{setLab(await api<Lab>('/lab'));await refresh();}}/>:<Empty title="正在读取训练结果"/>)}
          {page==='experiments'&&(lab?<ExperimentView experiments={lab.experiments}/>:<Empty title="正在读取对照实验"/>)}
          {page==='data'&&(data?<DataCenter data={data} busy={busy} run={run} refresh={refresh} onNewSession={newSession}/>:<Empty title="正在读取数据"/>)}
          {page==='library'&&<LibraryView items={library}/>}
          {page==='history'&&<HistoryView history={history} busy={busy} onExport={()=>run('导出记录',async()=>{await downloadHistory();})} onContinue={d=>{setRecord(d);go('decision');}}/>}
        </>}
        <footer className="main-footer"><span>深谋远虑 · 让决策有依据，让学习可追踪</span><span>研究原型 / 企业执行需业务审核</span></footer>
      </main>
    </div>
    {busy&&dashboard&&<div className="busy-indicator" role="status"><LoaderCircle size={15} className="spinning"/>{busy}…</div>}
  </div>;
}

function Overview({dashboard:d,onDecision}:{dashboard:Dashboard;onDecision:()=>void}) {
  const m=d.metrics,prior=d.series.at(-2);
  const cards=[{label:'销售收入',value:money(m.revenue),note:'最新观察日',change:prior&&prior.revenue?`${m.revenue>=prior.revenue?'+':''}${pct(m.revenue/prior.revenue-1)}`:null},
    {label:'营销 ROI',value:fmt(m.roi),note:'营销贡献利润 / 营销投入'},
    {label:'广告 CAC',value:money(m.cac,2),note:'广告费 / 新客人数'},
    {label:'订单转化率',value:pct(m.conversion_rate),note:'订单 / 点击'},
    {label:'回流客户占比',value:pct(m.repeat_purchase_rate),note:'复购代理，非真实复购率'},
    {label:'库存压力',value:fmt(m.inventory_pressure),note:`分仓库存 ${fmt(m.inventory_level,0)} 件`},
    {label:'贡献利润率',value:pct(m.profit_margin),note:d.quality.cost_method},
    {label:'广告投入',value:money(m.advertising_budget),note:'最新观察日渠道合计'}];
  const risks=[m.roi!=null&&m.roi<0?'当前营销贡献利润为负，需要审视渠道投入':null,m.inventory_pressure!=null&&m.inventory_pressure>.65?'库存覆盖偏高，库存消化值得优先评估':null,m.cac!=null&&m.cac>80?'获客成本较高，关注渠道边际效率':null].filter(Boolean);
  const factors=d.state.factors;
  return <><div className="overview-intro"><div><span className="small-label">当前观察日</span><strong>{m.date||d.quality.end}</strong></div><span>指标来自后端计算 · {d.quality.latest_result_source||d.quality.label}</span></div>
    <div className="metric-grid">{cards.map((c,i)=><div key={c.label} className="metric-card"><div className="metric-label">{c.label}<span className={`metric-glyph glyph-${i}`}><ChartNoAxesCombined size={13}/></span></div><div className="metric-value">{c.value}</div><div className="metric-note">{c.change&&<span className="delta">{c.change}</span>}{c.note}</div></div>)}</div>
    <div className="grid-two wide-left"><Panel title="销售收入趋势" subtitle="最近 30 个观察日，含节日与市场波动" extra={<Badge>日收入 / 元</Badge>}><RevenueChart series={d.series}/></Panel><Panel title="渠道投入与收入" subtitle="最新观察日 · 独立渠道口径">{m.channels?.length?<ChannelChart series={m.channels}/>:<Empty title="本期未填报渠道明细" detail="实际结果只有合计指标，系统不会编造各渠道收入。"/>}</Panel></div>
    <div className="grid-two wide-left"><Panel title="当前经营关注" extra={<Target size={17} className="muted"/>}><div className="insight-list">{risks.length?risks.map((x,i)=><div key={i} className="insight"><span className="insight-number">0{i+1}</span><div><h3>{x}</h3><p>{i===0?'收入变化需要结合商品成本、促销和退货一起判断。':'在当前目标与约束下比较动作，再记录实际经营结果。'}</p></div><ArrowUpRight size={17}/></div>):<p className="body-copy">当前指标没有触发预设阈值，仍需结合业务周期判断。</p>}</div><button className="text-link" onClick={onDecision}>带着这些指标进入决策中心<ArrowRight size={15}/></button></Panel><Panel title="经营因子速览" subtitle="数值来自当前状态，不代表因果重要性"><FactorSummary title="绩效信号" factors={factors.filter(x=>x.category==='performance'&&x.available).slice(0,2)} tone="green"/><FactorSummary title="惩罚信号" factors={factors.filter(x=>x.category==='penalty'&&x.available).sort((a,b)=>b.normalized-a.normalized).slice(0,2)} tone="amber"/><div className="factor-summary"><span className="small-label">外部扰动</span><p>上传数据没有实测外部信号；可在问题中补充，并保留“语义信号”来源。</p></div></Panel></div>
    <Panel title="从数据到反馈的决策闭环" subtitle="当前数据可直接用于决策；执行结果会进入下一轮学习"><Flow stage={d.active_decision?d.active_decision.status==='executed'?3:2:0}/></Panel>
  </>;
}
function FactorSummary({title,factors,tone}:{title:string;factors:Factor[];tone:'green'|'amber'}) { return <div className="factor-summary"><span className="small-label">{title}</span><div>{factors.map(f=><span className={`factor-chip ${tone}`} key={f.name}>{f.name}<strong>{fmt(f.raw)}</strong></span>)}</div></div>; }

function DecisionCenter({dashboard,record,busy,run,onCreated,onExecute,onFeedback,onCancel,onEnd}:{dashboard:Dashboard;record:Decision|null;busy:string;run:(s:string,f:()=>Promise<void>)=>Promise<void>;onCreated:(d:Decision)=>Promise<void>;onExecute:(d:Decision,b?:unknown)=>void;onFeedback:(d:Decision,b:unknown)=>void;onCancel:(d:Decision)=>void;onEnd:(d:Decision)=>void}) {
  const [question,setQuestion]=useState('最近抖音获客成本越来越高，但是库存积压，老客户回流还不错，我应该怎么调整营销策略？');
  const [profile,setProfile]=useState('balanced_growth'),[budget,setBudget]=useState(18000),[floor,setFloor]=useState(20),[margin,setMargin]=useState(.15),[promo,setPromo]=useState(false),[stopped,setStopped]=useState<string[]>([]),[custom,setCustom]=useState(false),[weights,setWeights]=useState<Record<string,number>>({});
  const active=dashboard.active_decision;
  useEffect(()=>{setWeights(dashboard.profiles.find(p=>p.name===profile)?.weights||{});},[profile,dashboard.profiles]);
  const submit=(e:React.FormEvent)=>{e.preventDefault();run('计算营销决策',async()=>{const d=await post<Decision>('/decisions',{question,reward_profile:profile,weights:custom?weights:null,constraints:{max_daily_budget:budget,min_price:floor,min_gross_margin:margin,prohibited_promotions:promo,stopped_channels:stopped}});await onCreated(d);});};
  return <>
    <Flow stage={record?.transition?.update?5:active?.status==='executed'?3:record?2:0}/>
    <div className="grid-two decision-input-grid"><Panel title="描述当前营销问题" subtitle="语义提取保留证据，实测指标优先"><form onSubmit={submit}><label className="field-label" htmlFor="question">经营问题</label><textarea id="question" value={question} onChange={e=>setQuestion(e.target.value)} rows={4} maxLength={1600} required/><div className="question-presets"><button type="button" onClick={()=>setQuestion('国庆大促即将到来，竞品降价，库存较多，怎样在毛利底线内调整？')}>大促与库存</button><button type="button" onClick={()=>setQuestion('流量下降，抖音获客成本高，如何控制广告投入？')}>获客效率</button></div>
      <div className="form-row"><div><label className="field-label" htmlFor="profile">当前企业目标</label><select id="profile" value={profile} onChange={e=>setProfile(e.target.value)}>{dashboard.profiles.map(p=><option key={p.name} value={p.name}>{p.label}</option>)}</select></div><div><label className="field-label" htmlFor="budget">每日广告预算上限 / 元</label><input id="budget" type="number" value={budget} min={0} max={1000000} onChange={e=>setBudget(Number(e.target.value))}/></div></div>
      <details className="settings-details"><summary><SlidersHorizontal size={14}/>业务约束与奖励权重<ChevronDown size={14}/></summary><div className="form-row"><div><label className="field-label" htmlFor="floor">成交价底线 / 元</label><input id="floor" type="number" min={1} value={floor} onChange={e=>setFloor(Number(e.target.value))}/></div><div><label className="field-label" htmlFor="margin">毛利底线 / 小数</label><input id="margin" type="number" min={0} max={.9} step={.01} value={margin} onChange={e=>setMargin(Number(e.target.value))}/></div></div><label className="check-field"><input type="checkbox" checked={promo} onChange={e=>setPromo(e.target.checked)}/>禁止新增促销</label><div className="field-label">停用渠道</div><div className="checks-inline">{['抖音','小红书','淘宝','搜索广告','私域'].map(ch=><label key={ch} className="check-field"><input type="checkbox" checked={stopped.includes(ch)} onChange={e=>setStopped(e.target.checked?[...stopped,ch]:stopped.filter(x=>x!==ch))}/>{ch}</label>)}</div><label className="check-field"><input type="checkbox" checked={custom} onChange={e=>setCustom(e.target.checked)}/>自定义目标权重（系统自动归一化）</label>{custom&&<div className="weights-grid">{Object.entries(weights).map(([k,v])=><label key={k}>{REWARD_LABEL[k]}<input type="number" min={0} step={.01} value={v} onChange={e=>setWeights({...weights,[k]:Number(e.target.value)})}/></label>)}</div>}</details>
      {active&&<Notice>已有一轮决策正在进行。完成执行反馈或取消首轮草稿后，可新建问题。</Notice>}
      <button className="button primary full" disabled={!!busy||!!active||question.trim().length<2} type="submit"><Workflow size={16}/>生成 Deep SARSA 决策<ArrowRight size={15}/></button></form></Panel>
      <Panel title="决策依据与职责" subtitle="理解、选动作、解释各有边界"><div className="role-list"><div><span className="role-index">01</span><div><strong>语义理解</strong><p>{dashboard.llm.available?'LLM 通过严格结构化输出提取业务信号。':'当前用规则解析。API 接通后切换为 LLM，保留调用来源。'}</p></div></div><div><span className="role-index">02</span><div><strong>Deep SARSA 选择动作</strong><p>读取 72 维状态，在合法动作中选择最高 Q 值；预算与毛利约束先执行。</p></div></div><div><span className="role-index">03</span><div><strong>解释已选结果</strong><p>解释层接收已经确定的动作，不能改写它。Q 值是累计回报估计。</p></div></div></div><div className="model-meta"><span>当前模型</span><code>{dashboard.model_version}</code><span>训练来源</span><strong>合成营销环境</strong><span>最新数据</span><strong>{dashboard.metrics.date}</strong></div><Notice tone="amber">仿真模型尚未验证企业实际效果。先比较、再执行、再记录结果。</Notice></Panel></div>
    {record&&<DecisionDetail decision={record} busy={busy} actionable={active?.id===record.id} onExecute={onExecute} onFeedback={onFeedback} onCancel={onCancel} onEnd={onEnd}/>}
  </>;
}

function DecisionDetail({decision:d,busy,actionable=false,onExecute,onFeedback,onCancel,onEnd}:{decision:Decision;busy:string;actionable?:boolean;onExecute?:(d:Decision,b?:unknown)=>void;onFeedback?:(d:Decision,b:unknown)=>void;onCancel?:(d:Decision)=>void;onEnd?:(d:Decision)=>void}) {
  const [chosen,setChosen]=useState(d.action_name),[reason,setReason]=useState('');
  const [forecast,setForecast]=useState(''),[reasonCategory,setReasonCategory]=useState('business_evidence'),[supporting,setSupporting]=useState(false),[anchor,setAnchor]=useState(''),[conflict,setConflict]=useState(false);
  useEffect(()=>{setChosen(d.action_name);setReason('');setForecast('');setReasonCategory('business_evidence');setSupporting(false);setAnchor('');setConflict(false);},[d.id,d.action_name]);
  const interpretation=d.explanation;
  return <div className="decision-result"><div className="result-head"><div className="result-icon"><Workflow size={22}/></div><div><div className="small-label">DEEP SARSA · 决策结果</div><h2>{d.action_label}</h2><p>{PROFILE_LABEL[d.reward_profile]} · {shortDate(d.timestamp)} · 模型 {d.model_version}</p></div><Badge tone={d.status==='updated'||d.status==='terminal'?'green':'blue'}>{STATUS[d.status]||d.status}</Badge></div>
    <div className="result-stats"><div><span>决策来源</span><strong>{d.decision_source}</strong></div><div><span>解释来源</span><strong>{d.explanation_source==='LLM'?'LLM':'模板解释'}</strong></div><div><span>动作 Q 值 / 累计回报</span><strong>{fmt(d.q_selected,4)}</strong></div><div><span>下一期仿真奖励均值</span><strong>{fmt(d.expected_reward.mean,4)}</strong><small>区间 {fmt(d.expected_reward.low,3)} – {fmt(d.expected_reward.high,3)}</small></div></div>
    <Notice>{d.expected_reward.source}。Q 值与下一期奖励口径不同。</Notice>
    <div className="grid-two"><Panel title="问题提取与信号" extra={<Badge tone={d.semantic.source==='LLM'?'green':'amber'}>{d.semantic.source==='LLM'?'LLM 结构化输出':'规则解析'}</Badge>}><div className="signal-grid"><div><span>库存压力描述</span><strong>{d.semantic.signals.inventory_pressure}</strong></div><div><span>抖音 CAC 描述</span><strong>{d.semantic.signals.douyin_cac}</strong></div><div><span>客户回流描述</span><strong>{d.semantic.signals.repeat_purchase}</strong></div><div><span>竞品压力信号</span><strong>{fmt(d.semantic.signals.competitor_intensity)}</strong></div></div><p className="evidence-quote">“{d.semantic.signals.evidence[0]||'没有可引用的原文证据'}”</p><p className="fine-print">定性描述保留为证据；库存、CAC 等实测指标不会被文本覆盖。外部信号为语义映射假设。</p>{d.semantic.fallback_reason&&<p className="fine-print">{d.semantic.fallback_reason}</p>}</Panel>
      <Panel title="为什么选择这个动作" subtitle="解释层只能解释已确定的结果"><p className="explanation-summary">{interpretation.summary}</p><ul className="simple-list">{interpretation.reasons.map((x,i)=><li key={i}>{x}</li>)}</ul><div className="watch-metrics">关注指标：{interpretation.watch_metrics.join('、')}</div><p className="fine-print">{interpretation.limitations.join('；')}</p></Panel></div>
    <div className="grid-two wide-left"><Panel title="所有动作的 Q 值" subtitle="灰色动作已屏蔽；蓝色为模型建议，数值来自神经网络" extra={<Badge>{d.q_values.filter(x=>x.legal).length} / 18 合法</Badge>}><QChart values={d.q_values} selected={d.action}/><details className="settings-details"><summary>查看 Q 数值与屏蔽原因<ChevronDown size={14}/></summary><div className="table-scroll"><table><thead><tr><th>动作</th><th>Q 值</th><th>约束</th></tr></thead><tbody>{d.q_values.map(q=><tr key={q.name}><td>{q.label}</td><td>{fmt(q.q,5)}</td><td>{q.legal?'合法':q.reasons.join('；')}</td></tr>)}</tbody></table></div></details></Panel><Panel title="非理性决策风险信号" subtitle="历史规则计算，缺少证据则不评分"><BiasList items={d.bias}/><Notice tone="amber">这些是操作模式的风险信号，不能据此诊断人员心理或归因个人。</Notice></Panel></div>
    <Panel title="当前因子与状态向量" subtitle={`${d.state_vector.length} 维 · 因子定义 ${d.factor_signature}`}><FactorTable factors={d.factor_values}/><details className="settings-details"><summary>查看模型实际输入 State Vector<ChevronDown size={14}/></summary><div className="vector-grid">{d.state_vector.map((x,i)=><div key={i}><span>s[{i}]</span><strong>{fmt(x,3)}</strong></div>)}</div><p className="fine-print">前 30 项为标准化因子，随后 30 项为存在标记，最后 12 项为经营目标权重。</p></details></Panel>
    {actionable&&d.status==='draft'&&onExecute&&<Panel title={d.parent_decision?'确认下一实际动作，完成上一轮学习':'确认策略执行'} subtitle="建议记录与执行记录分别保存，人工修改也会保留原因"><div className="execution-row"><div><label className="field-label" htmlFor="executed-action">实际执行动作</label><select id="executed-action" value={chosen} onChange={e=>setChosen(e.target.value)}>{d.q_values.filter(q=>q.legal).map(q=><option key={q.name} value={q.name}>{q.label}</option>)}</select></div>{chosen!==d.action_name&&<div><label className="field-label" htmlFor="override-reason">人工调整理由</label><input id="override-reason" value={reason} onChange={e=>setReason(e.target.value)} placeholder="简述业务原因"/></div>}<button className="button primary" disabled={!!busy||(chosen!==d.action_name&&!reason.trim())} onClick={()=>onExecute(d,{action_name:chosen,reason:chosen!==d.action_name?reason:null,reason_category:reasonCategory,forecast_revenue:forecast?Number(forecast):null,anchor_value:anchor?Number(anchor):null,supporting_experiment:supporting,current_evidence_conflict:conflict})}><Check size={15}/>确认执行此动作</button>{!d.parent_decision&&onCancel&&<button className="button subtle" disabled={!!busy} onClick={()=>onCancel(d)}>取消草稿</button>}{d.parent_decision&&onEnd&&<button className="button subtle" disabled={!!busy} onClick={()=>onEnd(d)}>结束周期，不执行下一动作</button>}</div><details className="settings-details"><summary>可选：记录预测与决策依据，支持后续偏差分析<ChevronDown size={14}/></summary><div className="form-row"><div><label className="field-label" htmlFor="execution-forecast">本期收入预测 / 元</label><input id="execution-forecast" type="number" min={0} value={forecast} onChange={e=>setForecast(e.target.value)} placeholder="留空表示未做预测"/></div><div><label className="field-label" htmlFor="reason-category">实际执行依据</label><select id="reason-category" value={reasonCategory} onChange={e=>setReasonCategory(e.target.value)}><option value="business_evidence">当前经营数据与模型</option><option value="competitor_follow">跟随竞品动作</option><option value="historical_anchor">参照历史价格或预算</option></select></div></div>{reasonCategory==='competitor_follow'&&<label className="check-field"><input type="checkbox" checked={supporting} onChange={e=>setSupporting(e.target.checked)}/>已有支持这次跟随投入的对照实验</label>}{reasonCategory==='historical_anchor'&&<><label className="field-label" htmlFor="anchor-value">参照的历史价格 / 预算<input id="anchor-value" type="number" min={0} value={anchor} onChange={e=>setAnchor(e.target.value)}/></label><label className="check-field"><input type="checkbox" checked={conflict} onChange={e=>setConflict(e.target.checked)}/>当前证据与该历史参照存在冲突</label></>}</details>{d.parent_decision&&<Notice>确认实际 A′ 才完成 SARSA 更新；也可结束周期，按终止状态只使用 Reward 更新。</Notice>}</Panel>}
    {actionable&&d.status==='executed'&&onFeedback&&<FeedbackForm key={d.id} decision={d} busy={busy} onFeedback={onFeedback}/>}
    {d.actual_reward&&<RewardView reward={d.actual_reward} source={d.user_feedback?.provenance.label||''}/>}
    {(d.transition?.update||d.previous_update)&&<UpdateView update={d.transition?.update||d.previous_update!} transition={d.transition}/>}
  </div>;
}

function FeedbackForm({decision:d,busy,onFeedback}:{decision:Decision;busy:string;onFeedback:(d:Decision,b:unknown)=>void}) {
  const [mode,setMode]=useState('simulation'),[rating,setRating]=useState('neutral'),[terminal,setTerminal]=useState(false),[values,setValues]=useState<Record<string,string>>({});
  const fields=[['revenue','销售收入 / 元',true],['profit','营销贡献利润 / 元',true],['roi','营销 ROI / 比值',true],['cac','广告 CAC / 元',true],['inventory_level','期末分仓库存 / 件',true],['conversion_rate','转化率 / 小数',true],['sales','本期销量 / 件',false],['advertising_cost','实际广告费 / 元',false],['promotion_cost','额外促销费 / 元',false],['repeat_purchase_rate','回流客户占比 / 小数',false],['inventory_turnover','日库存周转 / 小数',false],['new_customer_ratio','新客占比 / 小数',false],['return_rate','退货率 / 小数',false]] as const;
  const submit=(e:React.FormEvent)=>{e.preventDefault();const outcome=mode==='actual'?Object.fromEntries(fields.map(([k])=>[k,values[k]?.trim()?Number(values[k]):null])):null;onFeedback(d,{mode,rating,terminal,outcome});};
  return <Panel title="经营结果反馈" subtitle="主观评价单独保存，Reward 只由经营指标计算"><form onSubmit={submit}><div className="feedback-controls"><div><label className="field-label" htmlFor="feedback-mode">结果来源</label><select id="feedback-mode" value={mode} onChange={e=>setMode(e.target.value)}><option value="simulation">运行合成环境演示</option><option value="actual">填写企业实际经营结果</option></select></div><div><label className="field-label" htmlFor="rating">主观评价</label><select id="rating" value={rating} onChange={e=>setRating(e.target.value)}><option value="effective">有效</option><option value="neutral">一般</option><option value="ineffective">无效</option></select></div><label className="check-field"><input type="checkbox" checked={terminal} onChange={e=>setTerminal(e.target.checked)}/>结束本轮经营周期</label></div>
    {mode==='actual'?<><Notice>比率请输入小数，例如 4% 输入 0.04。利润口径为扣除商品、广告、额外促销与退货损失后的营销贡献利润。未填可选指标保持缺失。</Notice><div className="feedback-fields">{fields.map(([key,label,required])=><div key={key}><label className="field-label" htmlFor={`outcome-${key}`}>{label}{required&&<span className="required"> *</span>}</label><input id={`outcome-${key}`} type="number" step="any" min={key==='profit'||key==='roi'?undefined:0} max={['conversion_rate','repeat_purchase_rate','inventory_turnover','new_customer_ratio','return_rate'].includes(key)?1:undefined} required={required} value={values[key]||''} placeholder={required?'必填':'可选，留空表示未知'} onChange={e=>setValues({...values,[key]:e.target.value})}/></div>)}</div></>:<Notice tone="amber">将使用已确认动作运行一个可复现的合成环境。结果、Reward 和在线更新都会记录为“仿真”，不会当成企业真实反馈。</Notice>}
    <div className="form-footer"><p>{terminal?'终止状态只以实际 Reward 更新，不使用下一动作。':'提交后生成下一状态与下一决策；确认下一实际动作后再更新。'}</p><button className="button primary" type="submit" disabled={!!busy}><RefreshCw size={15}/>{mode==='simulation'?'运行仿真并提交结果':'提交实际经营结果'}</button></div></form></Panel>;
}
function BiasList({items}:{items:Bias[]}) { return <div className="bias-list">{items.map(x=><div key={x.name}><div className="bias-top"><strong>{x.label}</strong><span>{x.score==null?'证据不足':fmt(x.score)}</span></div><div className="mini-track"><i style={{width:`${(x.score||0)*100}%`}}/></div><details><summary>{x.score==null?'需要补充历史记录':'查看规则证据'}</summary><pre>{JSON.stringify(x.evidence,null,2)}</pre></details></div>)}</div>; }
function FactorTable({factors}:{factors:Factor[]}) { return <div className="table-scroll factor-table"><table><thead><tr><th>因子 / 业务含义</th><th>类别</th><th>原始值</th><th>标准化值</th><th>数据来源</th></tr></thead><tbody>{factors.map(f=><tr key={f.name}><td><strong>{f.name}</strong><small>{f.description}</small></td><td>{CATEGORY[f.category]||f.category}</td><td>{fmt(f.raw)}</td><td><div className="factor-bar"><i style={{width:`${f.normalized*100}%`}}/><span>{f.available?fmt(f.normalized,3):'缺失'}</span></div></td><td className="source-cell">{f.provenance||f.source}{f.clipped&&<Badge tone="amber">已截断</Badge>}</td></tr>)}</tbody></table></div>; }
function RewardView({reward:r,source}:{reward:Reward;source:string}) { return <Panel title="Reward 计算明细" subtitle={source} extra={<Badge tone="blue">总奖励 {fmt(r.total,5)}</Badge>}><Notice>可用指标的权重覆盖 {pct(r.coverage)}。未填指标不贡献奖励；覆盖不同的记录不宜直接比较。目标：{PROFILE_LABEL[r.profile]}。</Notice><div className="table-scroll"><table><thead><tr><th>指标</th><th>原始值</th><th>标准化</th><th>权重</th><th>贡献</th></tr></thead><tbody>{r.contributions.map(x=><tr key={x.name}><td>{REWARD_LABEL[x.name]}</td><td>{fmt(x.raw)}</td><td>{x.available?fmt(x.normalized,4):'缺失'}</td><td>{pct(x.weight)}</td><td className={x.contribution<0?'negative':'positive'}>{fmt(x.contribution,5)}</td></tr>)}</tbody></table></div></Panel>; }
function UpdateView({update:u,transition}:{update:NonNullable<Decision['previous_update']>;transition:Decision['transition']}) { return <Panel title="SARSA 更新凭证" subtitle="实际计算值，可在导出的完整记录中核查" extra={<Badge tone="green">模型更新 #{u.updates}</Badge>}><div className="update-equation"><span>TD Target</span><strong>{fmt(u.target,5)}</strong><b>=</b><span>Reward</span><strong>{fmt(u.reward,5)}</strong>{!u.terminal&&<><b>+</b><span>γ × Q(s′, A′)</span><strong>Q = {fmt(u.bootstrap_q,5)}</strong></>}</div><div className="result-stats compact"><div><span>Huber Loss</span><strong>{fmt(u.loss,6)}</strong></div><div><span>更新前 Q(s, A)</span><strong>{fmt(u.q_before,5)}</strong></div><div><span>下一实际动作索引</span><strong>{u.terminal?'终止状态':u.next_action}</strong></div><div><span>梯度范数</span><strong>{fmt(u.gradient_norm,4)}</strong></div></div><p className="fine-print">{u.algorithm} · {transition?.model_version_after||'完整版本见上一轮历史'}。该凭证证明执行了参数更新，不证明营销效果已改善。</p></Panel>; }

function Laboratory({lab,busy,run,onTrained}:{lab:Lab;busy:string;run:(s:string,f:()=>Promise<void>)=>Promise<void>;onTrained:()=>Promise<void>}) {
  const [report,setReport]=useState<TrainingReport|null>(null),[curves,setCurves]=useState<Curve[]|null>(null),[episodes,setEpisodes]=useState(40),[seed,setSeed]=useState(42),[lr,setLr]=useState(.0007),[gamma,setGamma]=useState(.92),[running,setRunning]=useState(false),[progress,setProgress]=useState(0),[admin,setAdmin]=useState('');
  const training=report||lab.training; const chartCurves=curves||training?.curves||[];
  const trainNow=()=>run('启动仿真训练',async()=>{
    const tokenHeaders: Record<string,string>=admin?{'X-Admin-Token':admin}:{};
    const job=await api<{id:string}>('/lab/train',{method:'POST',headers:tokenHeaders,body:JSON.stringify({episodes,seed,learning_rate:lr,gamma})});setRunning(true);setCurves([]);setProgress(0);
    const poll=async()=>{
      try{const next=await api<{status:string;progress:number;curves:Curve[];report?:TrainingReport;error?:string}>(`/lab/jobs/${job.id}`);setProgress(next.progress);setCurves(next.curves);
        if(next.status==='completed'){setRunning(false);if(next.report)setReport(next.report);await onTrained();}
        else if(next.status==='failed'){setRunning(false);run('训练结果',async()=>{throw new Error(next.error||'训练失败');});}
        else setTimeout(poll,1500);
      }catch(e){setRunning(false);run('训练状态',async()=>{throw e;});}
    };setTimeout(poll,800);
  });
  return <><div className="metric-grid lab-metrics"><MiniMetric label="预训练轮数" value={String(training?.curves.length||0)} note="真实环境交互轨迹"/><MiniMetric label="模型累计更新" value={fmt(lab.updates,0)} note="包含预训练与本会话反馈"/><MiniMetric label="当前 Epsilon" value={fmt(lab.epsilon,3)} note="在线推荐使用贪心合法动作"/><MiniMetric label="输入 / 输出" value="72 / 18" note="神经网络连续状态映射"/></div>
    <Notice tone="amber">{training?.source||'尚未运行预训练'}。曲线保留真实波动；初步配置并未证明预训练或语义信号稳定优于其他策略。</Notice>
    <div className="grid-two"><Panel title="训练平均 Reward" subtitle="浅线为实际每轮结果，深线为 10 轮移动均值"><TrainingChart curves={chartCurves} kind="reward"/></Panel><Panel title="损失与探索率" subtitle="Huber Loss 与 Epsilon 同轴，仅用于观察训练过程"><TrainingChart curves={chartCurves} kind="loss"/></Panel></div>
    {training?.before_after&&<Panel title="同一独立测试场景的训练前后对比" subtitle="来自保存的预训练实验，不把随机初始化当业务基线"><div className="before-after"><div><span>训练前平均 Reward</span><strong>{fmt(training.before_after.before.average_reward,4)}</strong></div><ArrowRight size={24}/><div><span>训练后平均 Reward</span><strong>{fmt(training.before_after.after.average_reward,4)}</strong></div><p>如实显示提升或下降。当前结果需要进一步校准环境、训练稳定性与业务数据。</p></div></Panel>}
    <div className="grid-two wide-left"><Panel title="因子预测重要性" subtitle="独立时间窗口上置换后 MSE 的变化"><ImportanceChart items={lab.importance.importance}/><p className="fine-print">{lab.importance.target}；训练 {lab.importance.train_n||0} 条，测试 {lab.importance.test_n||0} 条。负值表示该置换未降低预测性能。</p></Panel><Panel title="运行一次新的训练" subtitle="以本会话最新指标校准随机环境，不直接从 CSV 学最优策略"><div className="form-row"><label className="field-label">Episodes<input aria-label="训练轮数" type="number" min={10} max={300} value={episodes} onChange={e=>setEpisodes(Number(e.target.value))}/></label><label className="field-label">Seed<input aria-label="随机种子" type="number" min={0} value={seed} onChange={e=>setSeed(Number(e.target.value))}/></label></div><div className="form-row"><label className="field-label">Learning Rate<input aria-label="学习率" type="number" min={.00001} step={.0001} value={lr} onChange={e=>setLr(Number(e.target.value))}/></label><label className="field-label">Gamma<input aria-label="折扣因子" type="number" min={0} max={.99} step={.01} value={gamma} onChange={e=>setGamma(Number(e.target.value))}/></label></div><label className="field-label">管理员令牌（本地默认可留空）<input type="password" autoComplete="off" value={admin} onChange={e=>setAdmin(e.target.value)} placeholder="不会保存到浏览器"/></label><button className="button primary full" disabled={!!busy||running} onClick={trainNow}>{running?<LoaderCircle className="spinning" size={15}/>:<Play size={15}/>}{running?`正在训练 ${progress} / ${episodes}`:'开始训练本会话模型'}</button><p className="fine-print">训练会保存新模型；活动决策期间禁止替换。公网训练需管理员令牌。</p></Panel></div>
    <Panel title="因子分析明细" subtitle="把相关性、预测重要性与策略敏感度分别观察"><ImportanceTable analysis={lab.importance}/></Panel>
    <div className="grid-two"><Panel title="网络与算法参数"><pre className="network-code">{lab.network}</pre><div className="parameter-grid">{Object.entries(lab.config).map(([k,v])=><div key={k}><span>{k}</span><strong>{String(v)}</strong></div>)}</div></Panel><Panel title="最近反馈更新" subtitle="反馈转移和实际下一动作"><div className="transition-list">{lab.recent_transitions.length?lab.recent_transitions.map((t,i)=><div key={i}><Badge tone={t.update?'green':'amber'}>{t.update?'已更新':'等待下一动作'}</Badge><strong>R = {fmt(t.reward,4)}</strong><span>{t.source==='simulation'?'仿真结果':'实际填报'}</span><small>{t.terminal?'终止周期':`A′ = ${t.next_action_name||'尚未确认'}`}</small>{t.update&&<small>Loss {fmt(t.update.loss,5)} · TD Target {fmt(t.update.target,5)}</small>}</div>):<Empty title="尚无反馈转移" detail="确认策略执行并提交结果后，会出现更新凭证。"/>}</div></Panel></div>
  </>;
}
function MiniMetric({label,value,note}:{label:string;value:string;note:string}) { return <div className="metric-card"><div className="metric-label">{label}</div><div className="metric-value">{value}</div><div className="metric-note">{note}</div></div>; }
function ImportanceTable({analysis:a}:{analysis:FactorAnalysis}) { return <><Notice>{a.warning}</Notice><div className="table-scroll"><table><thead><tr><th>因子</th><th>置换重要性</th><th>重复置换标准差</th><th>Spearman</th><th>Q 敏感度</th></tr></thead><tbody>{a.importance.map(x=><tr key={x.name}><td><strong>{x.name}</strong>{!x.present&&<Badge>缺失</Badge>}</td><td>{fmt(x.permutation_mean,6)}</td><td>{fmt(x.permutation_std,6)}</td><td>{fmt(x.spearman,4)}</td><td>{fmt(x.q_sensitivity,5)}</td></tr>)}</tbody></table></div></>; }

function ExperimentView({experiments:e}:{experiments:Experiments|null}) {
  const [metric,setMetric]=useState<'average_reward'|'profit'|'cac'>('average_reward');
  if(!e)return <Empty title="尚无对照实验" detail="运行 scripts.pretrain 后载入真实实验结果。"/>;
  return <><Notice tone="amber">{e.source}。{e.semantic_boundary}</Notice><div className="experiment-meta"><Badge tone="blue">{e.test_seeds.length} 个独立测试种子</Badge><Badge>{e.horizon} 步 / 场景</Badge><span>共同种子：{e.test_seeds.join('、')}</span></div><Panel title="策略表现对比" subtitle="只绘制实际完成的实验组" extra={<select aria-label="实验比较指标" className="compact-select" value={metric} onChange={v=>setMetric(v.target.value as typeof metric)}><option value="average_reward">平均 Reward</option><option value="profit">日均营销贡献利润</option><option value="cac">广告 CAC</option></select>}><ExperimentChart groups={e.groups} metric={metric}/></Panel>
    <Panel title="完整实验结果" subtitle="未运行组保留，避免把规则输出伪装成 LLM"><div className="table-scroll"><table><thead><tr><th>实验策略</th><th>状态</th><th>平均 R</th><th>R 标准误</th><th>ROI</th><th>日均利润 / 元</th><th>转化率</th><th>CAC / 元</th><th>库存周转</th><th>Reward 波动</th><th>动作稳定性</th></tr></thead><tbody>{e.groups.map(g=><tr key={g.name}><td className="strategy-cell"><strong>{g.name}</strong>{g.reason&&<small>{g.reason}</small>}</td><td><Badge tone={g.status==='completed'?'green':'amber'}>{g.status==='completed'?'已运行':g.status==='failed'?'调用失败':'未运行'}</Badge></td><td>{fmt(g.summary?.average_reward,4)}</td><td>{fmt(g.summary?.reward_standard_error,4)}</td><td>{fmt(g.summary?.roi)}</td><td>{money(g.summary?.profit)}</td><td>{pct(g.summary?.conversion_rate)}</td><td>{money(g.summary?.cac,2)}</td><td>{pct(g.summary?.inventory_turnover)}</td><td>{fmt(g.summary?.reward_std,4)}</td><td>{pct(g.summary?.decision_stability)}</td></tr>)}</tbody></table></div><p className="fine-print">Reward 波动越低只代表回报更平稳；动作稳定性为相邻动作相同的比例，越高不一定更好。测试覆盖多个目标，不能仅凭单一均值判断策略优劣。</p></Panel>
    <Panel title="因子组消融" subtitle="固定已训练策略，在推理期屏蔽指定因子与存在标记"><div className="ablation-grid">{e.ablations.map(a=><div key={a.group}><span>{CATEGORY[a.group]}因子</span><strong>{fmt(a.reward,4)}</strong><small>相对完整输入 {a.difference_from_full>=0?'+':''}{fmt(a.difference_from_full,4)}</small><p>{a.masked_factors.join('、')}</p></div>)}</div><p className="fine-print">未重训的输入消融只反映该模型对输入的依赖；零差异可能来自缺失输入或未学到信息，不能认定该因子无价值。</p></Panel>
  </>;
}

function DataCenter({data:d,busy,run,refresh,onNewSession}:{data:Dataset;busy:string;run:(s:string,f:()=>Promise<void>)=>Promise<void>;refresh:()=>Promise<Dashboard>;onNewSession:()=>void}) {
  const [tab,setTab]=useState<'raw'|'metrics'|'factors'|'registry'>('raw'),[filter,setFilter]=useState('全部渠道');
  const rows=d.rows.filter(r=>filter==='全部渠道'||r.channel===filter).slice(-50);
  const upload=(file:File)=>run('导入并校验 CSV',async()=>{const form=new FormData();form.append('file',file);await api('/data/upload',{method:'POST',body:form});await refresh();});
  return <><div className="data-intro"><div><FileSpreadsheet size={27}/><div><h2>{d.quality.source==='demo'?'60 天多渠道营销演示数据':'企业上传的营销数据'}</h2><p>{d.quality.start} — {d.quality.end} · {d.quality.encoding} · 最大上传 2 MB</p></div></div><div className="heading-actions"><a className="button subtle" href="/api/data/sample.csv" download><Download size={15}/>下载 CSV 模板</a><label className={`button primary upload-button ${busy?'disabled':''}`}><Upload size={15}/>上传 CSV<input type="file" aria-label="上传企业 CSV" accept=".csv" disabled={!!busy} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.target.value='';}}/></label></div></div>
    <Notice>{d.quality.label}。库存使用渠道分仓口径；销售收入为折后收入，promotion_cost 仅填写额外补贴成本，避免重复扣除。</Notice>
    <div className="grid-two"><Panel title="数据质量与口径" extra={<Badge tone="green">已完成校验</Badge>}><ul className="simple-list">{[...d.quality.warnings,...d.quality.estimates].map((w,i)=><li key={i}>{w}</li>)}</ul><div className="data-buttons"><button className="button subtle" disabled={!!busy} onClick={()=>run('载入演示数据',async()=>{await post('/data/demo');await refresh();})}>重新载入演示数据</button><button className="button subtle" disabled={!!busy} onClick={onNewSession}>创建新演示会话</button></div></Panel><Panel title="模型输入状态" subtitle="缺失值以数值与存在标记共同编码"><div className="state-stats"><div><strong>{d.state.state_dim}</strong><span>状态维度</span></div><div><strong>{pct(d.state.coverage,0)}</strong><span>核心因子可用率</span></div><div><strong>30</strong><span>固定核心因子</span></div></div><p className="body-copy">指标缺失不会被文本随意填成实测值。模型与因子签名绑定，更改维度需要重训模型。</p><code className="signature">Factor signature · {d.state.signature}</code></Panel></div>
    <Panel title="经营数据与模型输入" extra={tab==='raw'?<select aria-label="筛选渠道" className="compact-select" value={filter} onChange={e=>setFilter(e.target.value)}>{['全部渠道','抖音','小红书','淘宝','搜索广告','私域'].map(ch=><option key={ch}>{ch}</option>)}</select>:undefined}><div className="tabs">{([['raw','原始记录'],['metrics','日指标'],['factors','因子与向量'],['registry','因子注册表']] as const).map(([k,label])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{label}</button>)}</div>
      {tab==='raw'&&<><div className="table-scroll"><table><thead><tr>{['日期','渠道','收入 / 元','广告费','额外促销费','曝光','点击','订单','新客','回流客户','库存','退货'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{['date','channel','revenue','advertising_cost','promotion_cost','impressions','clicks','orders','new_customers','returning_customers','inventory','returns'].map(k=><td key={k}>{typeof r[k]==='number'?fmt(r[k] as number,0):r[k]}</td>)}</tr>)}</tbody></table></div><p className="fine-print">展示筛选后的最近 50 行；导出模板包含完整示例。反馈结果另存于决策记录，原始 CSV 不被改写。</p></>}
      {tab==='metrics'&&<div className="table-scroll"><table><thead><tr><th>日期</th><th>收入</th><th>贡献利润</th><th>ROI</th><th>广告 CAC</th><th>转化率</th><th>回流占比</th><th>库存</th><th>库存周转</th></tr></thead><tbody>{d.daily.slice(-60).map((r,i)=><tr key={i}><td>{r.date}</td><td>{money(r.revenue)}</td><td>{money(r.profit)}</td><td>{fmt(r.roi)}</td><td>{money(r.cac,2)}</td><td>{pct(r.conversion_rate)}</td><td>{pct(r.repeat_purchase_rate)}</td><td>{fmt(r.inventory_level,0)}</td><td>{pct(r.inventory_turnover)}</td></tr>)}</tbody></table></div>}
      {tab==='factors'&&<><FactorTable factors={d.state.factors}/><details className="settings-details"><summary>实际状态向量<ChevronDown size={14}/></summary><div className="vector-grid">{d.state.vector.map((x,i)=><div key={i}><span>s[{i}]</span><strong>{fmt(x,3)}</strong></div>)}</div></details></>}
      {tab==='registry'&&<div className="table-scroll"><table><thead><tr><th>因子</th><th>类别</th><th>状态</th><th>范围</th><th>可控</th><th>所需数据</th></tr></thead><tbody>{d.registry.map(f=><tr key={f.name}><td><strong>{f.name}</strong><small>{f.description}</small></td><td>{CATEGORY[f.category]}</td><td><Badge tone={f.enabled?'blue':'neutral'}>{f.enabled?'核心注册':'候选待接入'}</Badge></td><td>{f.min_value} – {f.max_value}</td><td>{f.controllable?'可控':'观察'}</td><td>{f.source}</td></tr>)}</tbody></table></div>}
    </Panel>
  </>;
}
function LibraryView({items}:{items:LibraryComponent[]}) { return <><div className="library-banner"><LibraryBig size={34}/><div><h2>Marketing Decision Model Library</h2><p>组件以统一注册方式执行，输出经营指标与模型信息。新增组件无需改写决策引擎。</p></div><Badge tone="blue">{items.length} 个已实现组件</Badge></div><div className="library-grid">{items.map((x,i)=><section className="library-card" key={x.name}><div className="library-card-top"><span className="component-index">{String(i+1).padStart(2,'0')}</span><Badge tone="green">已实现</Badge></div><h2>{x.label}</h2><code>{x.name}</code><p>{x.description}</p><details><summary>查看当前计算结果<ChevronRight size={14}/></summary><pre>{JSON.stringify(x.output,null,2)}</pre><div className="fine-print">源码：{x.source_file}</div></details></section>)}</div></>; }

export { DecisionDetail, FeedbackForm, Laboratory, ExperimentView, DataCenter, HistoryView, FactorTable, LibraryView, RewardView, UpdateView };
function HistoryView({history,busy,onExport,onContinue}:{history:Decision[];busy:string;onExport:()=>void;onContinue:(d:Decision)=>void}) {
  const [open,setOpen]=useState<string|null>(null);
  return <Panel title="完整决策记录" subtitle="建议动作、实际动作、结果与参数更新各有记录" extra={<button className="button subtle" disabled={!!busy} onClick={onExport}><Download size={15}/>导出 JSON</button>}>{!history.length?<Empty title="还没有营销决策" detail="在决策中心创建第一轮，模型依据和反馈轨迹会保存在这里。"/>:<div className="history-list">{history.map(d=><div className="history-entry" key={d.id}><button className="history-summary" onClick={()=>setOpen(open===d.id?null:d.id)}><span className="history-dot"/><div><strong>{d.action_label}</strong><small>{d.question.slice(0,72)}</small></div><span>{shortDate(d.timestamp)}</span><Badge tone={['updated','terminal'].includes(d.status)?'green':'blue'}>{STATUS[d.status]}</Badge><ChevronDown size={16}/></button>{open===d.id&&<div className="history-expanded"><div className="history-metadata"><span>模型 {d.model_version}</span><span>决策：{d.decision_source}</span><span>解释：{d.explanation_source}</span><span>实际动作：{d.execution?.action_name||'尚未执行'}</span><span>目标：{PROFILE_LABEL[d.reward_profile]}</span></div><p className="body-copy">{d.explanation.summary}</p>{d.user_feedback&&<Notice tone={d.user_feedback.mode==='simulation'?'amber':'blue'}>{d.user_feedback.provenance.label}</Notice>}{d.actual_reward&&<RewardView reward={d.actual_reward} source="已保存奖励明细"/>}{d.transition?.update&&<UpdateView update={d.transition.update} transition={d.transition}/>}<details className="settings-details"><summary>完整因子、状态与动作记录<ChevronDown size={14}/></summary><FactorTable factors={d.factor_values}/><pre className="raw-json">{JSON.stringify({id:d.id,state_vector:d.state_vector,q_values:d.q_values,factor_importance:d.factor_importance,transition:d.transition},null,2)}</pre></details>{['draft','executed'].includes(d.status)&&<button className="button primary" onClick={()=>onContinue(d)}>继续执行与反馈<ArrowRight size={14}/></button>}</div>}</div>)}</div>}</Panel>;
}
